name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - main  # Change to the default branch of your repository if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: Puji2002@
          MYSQL_DATABASE: school_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-start-period=30s
          --health-retries=5
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'maven'
      #- run: java HelloWorldApp.java

      - name: Build with maven
        run: mvn clean install -X

      - name: Upload Test Reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/


      - name: Build the tests
        run: mvn test

