name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - main  # Change to the default branch of your repository if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      #set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      #- run: java HelloWorldApp.java

