name: Spring Boot CI Pipeline

on:
  push:
    branches:
      - main  # Change to the default branch of your repository if it's not 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

